# Generated by Django 5.1.2 on 2025-10-06 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiOcioNApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='puntuacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
