# Generated by Django 5.1.2 on 2025-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiOcioNApp', '0002_alter_review_puntuacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-fecha'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.CharField(default='Local', max_length=50),
        ),
    ]
